### ISSUE TITLE
Omit line endings in all relative editors/source control managers

### ISSUE THREAD

**Issue by thedoubl3j** [ansible-collections/azure#12]
While working on getting the collection staged for Automation Hub, I ran into a few errors in the sanity suite. These do not affect functionality but they can have an impact on the wider adoption and attract contributors. 

The specific errors I am referring to is that of line endings being automatically added to files either via an editor or by a git config. 

When multiple contributors are working on a file with different line endings the file switches back and forth between the two settings and the diffs usually show the entire file being rewritten.

This can be caught with `ansible-test` and will look something like 
```
ERROR: tests/integration/targets/azure_rm_securitygroup/tasks/main.yml:0:0: use "\n" for line endings instead of "\r\n"
```

This should be a relatively quick fix but as you fix this, do note that the `diffs` might reflect that the whole file has been rewritten, when in fact, it has not been.

**Comment by gavinfish** [comment]
@thedoubl3j So I need to change end line of sequence from CRLF to LF for all the files in this repo, right?

**Comment by Fred-sun** [comment]
@thedoubl3j Could you please respond to the questions in the comments above? Will go a long way towards solving the problem. Thank you very much!

**Comment by thedoubl3j** [comment]
you can change them yes, its more of a quality of life change than anything else, doesn't break anything but more just ease of eye sight. Apologies I missed this.

**Comment by Fred-sun** [comment]
> @thedoubl3j So I need to change end line of sequence from CRLF to LF for all the files in this repo, right?

@gavinfish Please take a look the feedback！ Thank you very much!

**Comment by Fred-sun** [comment]
File format converted, closed temporarily.
